### ISSUE TITLE
Edit input spreadsheet to accept fieldsets for pdfs in tables

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#109]
There are a four pages in the app (under reports and documents) that are tables of pdf files. This ticket is a placeholder to set up the input spreadsheet to accept the data and links to the pdf's. Only two of those pages have data for the Erin John's case study.

2nd column is for requisition, 3 column is for report
<img width="784" alt="screen shot 2019-03-06 at 10 30 33 am" src="https://user-images.githubusercontent.com/20425828/53904458-ff5a6980-3ffa-11e9-8661-171aa8c94f71.png">
<img width="787" alt="screen shot 2019-03-06 at 10 30 26 am" src="https://user-images.githubusercontent.com/20425828/53904459-ff5a6980-3ffa-11e9-91b9-83894131d995.png">

**Comment by bryan-gilbert** [comment]
This could be done via the spreadsheet as a standard page form with rows using the Asset Link input types. That provides files across all assignments.
To make this data vary for a Case/Assignment will require adding file upload feature. This is not huge except it introduces the question of needing data backups.  It might be possible to limit the file upload to seed content editors.

**Comment by bryan-gilbert** [comment]
Amanda, anything else needed or can we close this one?

**Comment by mandily-p** [comment]
Complete.
