### ISSUE TITLE
Checkbox fieldsets should display title in table, with checkboxes as values

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#114]
Fieldset title should be the table header, with values being listed in the table cell either with a comma, or on separate lines.
<img width="770" alt="Screen Shot 2019-03-11 at 3 01 11 PM" src="https://user-images.githubusercontent.com/20425828/54161807-9c107300-4410-11e9-995b-06ee859227c5.png">

**Comment by mandily-p** [comment]
Maybe we could handle this the same way that we handle select boxes in the input spreadsheet? I can come up with a label for each group if that's helpful.

**Comment by bryan-gilbert** [comment]
In the inputs sheet we will rename **select** to dropdown. Introduce new type **checkset**. Put the checboxes under this **checkset** group. Use the **checkset** to group the results in the table.
