### ISSUE TITLE
Documentation - Allow field labels to be links

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#124]
In a few instances, students need to be linked to external resources to search for codes and then input those codes into the associated fields. An example of this are the two fields on the `code lookup` screen. 

`SnomedCT` should link to TBD
`ICF` should like to TBD

**Comment by bryan-gilbert** [comment]
See row 85 of Current Visit 1 tab in the inputs sheet
https://docs.google.com/spreadsheets/d/1WQsjEGdxBJW5guR9ZIB1-mYuVu97IE_wQaNZ-2mW54M/edit#gid=453060087
It shows how to do a 'form_label' with html. Does that solve this issue?

**Comment by bryan-gilbert** [comment]
Documentation complete. See docs folder and Ehr-Defs-Input-Types.md
