### ISSUE TITLE
Allow instructors to set "evaluated" in the dashboard

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#138]
Add a column with a link for instructors to indicate something as evaluated. (ready to export)
Ideally instructors have the ability to select all and set the "evaluated" status or each assignment individually.

**Comment by bryan-gilbert** [comment]
The basics of evaluation are in the system.  Before closing this issue I'll just check that all the basics are working.   We have other issues open to discuss enhancements.
