### ISSUE TITLE
More info icon - hook up to spreadsheet

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#14]
A student may hover over an "i" icon to get additional information about how to fill in a field in a tooltip
Example: Field-level help (formatting, date/time pickers, keys)

Text to be used in these info boxes is located in the `helper text` column in the input spreadsheet

Used on pages (not an exhaustive list):
History: Psychosocial

**Comment by bryan-gilbert** [comment]
Bryan: Do helper text and suffix text at the same time

**Comment by mandily-p** [comment]
This looks like it's done to me.
