### ISSUE TITLE
Instructors should be sent to the first page of the assignment 

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#154]
As an instructor,
I want to see the first page of an **assignment** (whether viewing it or marking it)
To minimize the amount of time I need to navigate through the app.

Note that the students should still be delivered to the first **screen** of the app no matter which assignment they're working on.

**Comment by mandily-p** [comment]
We will need to discuss how to identify the first page of the assignment. (Diff on assignment vs submitted data?)

**Comment by bryan-gilbert** [comment]
We determined this is not really needed because the instructor only needs to go to a page once and they stay there as they progress through the class list.
