### ISSUE TITLE
Screen status - green dot

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#157]
If a user enters data on a screen, then display a green dot
If a user has not entered data on a screen, then display a red X
.. on the navigation side bar

Alternative:

For student:   Green dot means there is any data on the page. Empty circle? for no data.
For instructor: Green dot means there is student entered data (i.e. without the seed).
For content editor: Green dot means there is some data on the page.

Update - this feature is not for the student for the pilot.

**Comment by bryan-gilbert** [comment]
The data storage "ehrData" has new method hasDataForPagesList that provides an object with a property for each EHR page.  Each page property says if the page 
hasInstructor: if the student's work (that the instructor is reviewing) has data
hasStudent: if the student has added data to the page
hasSeed: if there is seed data
hasMerged: if the merge of the student data and seed data has some data for this page.

The NavPanel gets this object and provides it to it's child elements.
The NavPanelItem inspects the object for the page and displays green or orange or nothing.

**Comment by bryan-gilbert** [comment]
Next step, clean up appearance/colourings.  Consider how this now works for the student, instructor and seed developer.

**Comment by mandily-p** [comment]
I've styled this and submitted a PR. Logic is needed to display different icons in different situations.  Punting this one back to @bryan-gilbert

**Comment by bryan-gilbert** [comment]
I've redone the logic and created indicators for students.  Empty means there is data from the seed. Solid says there is data from the student's work.  How does this look @mandily-p ?  If it works then I'll need to go finish/check the logic for instructors and seed editors.
![image](https://user-images.githubusercontent.com/13558676/62650612-1d125e80-b90c-11e9-96e4-c806c07662a1.png)

**Comment by mandily-p** [comment]
I'd like to use the previous styling/icons instead of the shiny ones you've created. They're more in line with the flat design in the rest of the app :)

Otherwise, the functionality/representation looks good!
