### ISSUE TITLE
Checkbox to enable instructor the ability to edit content

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#158]
We need the ability to "hide" the edit content features.
Add a checkbox within the EHR special to enable seeing these.

-`Edit assignment`, `upload`, `download` buttons should be hidden on the Assignments screen
- `Develop EHR data` should be hidden
- If easy to do, give users a way to `view` the seed data.

**Comment by bryan-gilbert** [comment]
For prototype I put a checkbox at the bottom of all outside pages to control the isDevelopingContent mode. This mode is successfully restored if the user refreshes their browser.
Note the isDeveloper LTI role is not used at this time.  The server side code sets the property to true whenever the user is a teacher.  In the future, could set the property to match the incoming LTI roles.  And on the client side this role is ignored and the system only responds to the isDevelopingContent mode.
Note the experience as an instructor without edit content has a big hole. The instructor can no see the seed data in the EHR.
@mandily-p  do we want to add a means for instructors to get into a view only EHR to allow teachers to see the seed data?

**Comment by mandily-p** [comment]
I think this is solved by #324
