### ISSUE TITLE
Visit details - Move assignment time to the bottom of the page

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#164]
Current 
<img width="1032" alt="Screen Shot 2019-04-17 at 8 55 19 PM" src="https://user-images.githubusercontent.com/20425828/56335933-3de35800-6153-11e9-9913-0bb3c5958152.png">

Desired
<img width="1044" alt="Screen Shot 2019-04-17 at 8 56 51 PM" src="https://user-images.githubusercontent.com/20425828/56335967-6408f800-6153-11e9-84dc-c3c8c01380ed.png">

**Comment by bryan-gilbert** [comment]
Done a long time ago.
