### ISSUE TITLE
Case study data seeding

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#17]
Seeding db
Data from Health Case Study #1 and #2, plus additional details will need to be entered in the db

**3 parts**
Storage
Import

**Comment by bryan-gilbert** [comment]
Comment on how this is a work in progress:
Coming in my next commit will be a new set of default information based on the seed data in the INPUTS spreadsheet.   When a user is able to edit content (instructors at this time) and they open a seed in the EHR the screens will show default values for many form elements. None of these values are yet in the seed. They are defaults ready to be included.  For example, suppose you create a new seed and open the EHR.  The Erin Johns case data will appear as default values even though the seed itself is still empty.  (This weirdness is the work in progress part. I have not yet found a clean way to push these values into the seed.)  For now, the user will go screen to screen and edit the screen. They just need to turn on edit mode and then save the page. This will write the defaults (and any modifications) into the seed.
