### ISSUE TITLE
Create a Content Editing experience

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#191]
## Content (seed) editing needs to have a distinct experience

Instructors normally should not be able to edit the seed data content.
Content editors can edit seed content and they need to see the controls and pages that support this task.

- [] create an action that shows/hides all the seed editing functionality
- [] put a button for this action somewhere
- [] In the EHR the seed editor needs to be able to add data to some tables and the student user should only see the results.  Create a flag in the Inputs spreadsheet to control seed editing only and let this flag appear on page_form and table_row elements. (i.e. control the editing of the whole page form or a table)  see #163

**Comment by mandily-p** [comment]
This is complete.
