### ISSUE TITLE
Suffix labels

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#192]
### Allow page elements to have a suffix label 
As a EHR user I need to know what units some fields are measured in. This information is normally displayed as a label to the right of the field.
As a admin I need to define the suffix text in the Inputs spreadsheet.

### Implementation
-[] Import the suffix information from the Inputs and place into the page child element
-[] Provide a helper function to get this label
-[] In the display code on page load (mount), pull the suffix label and put into a data field. Add a data field into display code.

**Comment by mandily-p** [comment]
This is complete.
