### ISSUE TITLE
Calculated value - show "out of"

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#193]
### Show a "out of X' suffix beside calculated values 
As a user I need to know the total points of a calculated value to determine how important a result is.

### Implementation
-[] move the options list from the tableCells to the page children
- [] add a helper method to get options and use this in the display code instead of the current get from tableCells
- [] use the method that gets all the inputs for a calculated value. Use this to get the element's option list (use above method) and compute the max points per input. Sum all these max values.
- [] display this sum

**Comment by mandily-p** [comment]
Redundant with #78
