### ISSUE TITLE
Test refresh

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#199]
Test that users can refresh any page and the page reloads correctly. This test needs to be done on a production server to avoid the situations of localhost responding. It is sufficient to test reload of one EHR page as student, as instructor, as content editor. Test reload of any one dashboard page as instructor and as content editor.

**Comment by mandily-p** [comment]
Test that users can refresh any page and the page reloads correctly.  This test needs to be done on a production server to avoid the situations of localhost responding. It is sufficient to test reload of one EHR page as student, as instructor, as content editor.  Test reload of any one dashboard page as instructor and as content editor.

**Comment by bryan-gilbert** [comment]
Verified that the system works as expected
