### ISSUE TITLE
Add License into seed file

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#201]

**Comment by mandily-p** [comment]
@bryan-gilbert Is this done?

**Comment by bryan-gilbert** [comment]
The seed files now are saved and include the following text:
  "license": "This work is licensed under a Creative Commons Attribution 4.0 International License. See http://creativecommons.org/licenses/by/4.0/",

The importing methods now check for ...
if (!obj.license.includes('Creative Commons Attribution')) {
      return { invalidMsg: 'Seed licence must be Creative Commons Attribution'}
}

**Comment by bryan-gilbert** [comment]
We need to have a look at the license and see if it meets the project needs.
