### ISSUE TITLE
Seeding pdfs and images

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#21]
These are included as part of the seed
For example - consults, imaging reports, xrays, external resources, ultrasounds etc

**Comment by mandily-p** [comment]
@bryan-gilbert I'm stuck as to how I can get two files in one row (separate columns). I need to have the written report and also the xray associated with the report showing up before I can close this. 

Is this something that happens in the spreadsheet, or in the seeding phase? 

(There's two rows needed)

**Comment by mandily-p** [comment]
<img width="785" alt="Screen Shot 2019-05-24 at 9 57 20 PM" src="https://user-images.githubusercontent.com/20425828/58364838-f4cba580-7e6e-11e9-94e9-4eed1aa87863.png">

**Comment by bryan-gilbert** [comment]
I'll suggest something that is purely a prototyping solution ...  could we have six rows in the inputs spreadsheet 1. label 'Day 0', 2. asset 'COPD_xray.pdf' and 3 asset 'COPD xray report and then repeat for the second row?    Yet, I wonder what is the difference between the two assets? Aren't they the same but just different ways of displaying the link?

**Comment by mandily-p** [comment]
One is the picture, and one is the text data.
And I'm cool with the 6 row solution in the spreadsheet.

**Comment by mandily-p** [comment]
@bryan-gilbert Is it ok for me to go ahead and set this up in the input spreadsheet right now, or do I need to wait for you to set something up in the code?

**Comment by mandily-p** [comment]
@bryan-gilbert I've updated the input spreadsheet, but not exported it yet. I'll leave that to you when you update the code.
