### ISSUE TITLE
App gets narrow when modal is open on non-EHR pages

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#213]
Go to assignments
Click on `create a new assignment`
See page layout change behind modal

<img width="1673" alt="Screen Shot 2019-05-27 at 11 33 21 AM" src="https://user-images.githubusercontent.com/20425828/58435049-83107900-8073-11e9-8a0f-3269863a687d.png">

**Comment by viniciusarre** [comment]
@bryan-gilbert I couldn't replicate this. I believe this was fixed previously (although I don't quite remember the PR or Issue number), but I remember fixing a very similar bug, which the modal ended up breaking the layout. I think fixing that use case also managed to cover this one. Let me know your thoughts on it!

Thank you!
