### ISSUE TITLE
Instructors should not show up in the student list of assignments

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#221]
<img width="1664" alt="Screen Shot 2019-05-27 at 9 15 18 AM" src="https://user-images.githubusercontent.com/20425828/58595355-366c9f80-8225-11e9-9f00-9fb96a5d8bc8.png">

**Comment by bryan-gilbert** [comment]
Amanda found this is not a bug. The instructors can elect to launch the EHR in the role of a student. Hence they appear in the list of students who attempted the assignment.
