### ISSUE TITLE
Dashboard - Version number doesn't update

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#230]
I downloaded the Erin Johns master seed, made a few changes to mistakes I had make, and then uploaded it with the same file name, to the original seed. I see the changes in the app, but the version number didn't update in the dashboard.

![Screen Shot 2019-05-30 at 11 32 18 PM](https://user-images.githubusercontent.com/20425828/58686265-33f86b80-8333-11e9-8406-7da82422b71b.png)

**Comment by mandily-p** [comment]
@bryan-gilbert Is this even a problem? Now I'm wondering if it should be manual? What do other apps do?

**Comment by bryan-gilbert** [comment]
Not a bug, as designed, for now, the field is open to the user to set as they wish. This could become a feature for development if desired someday.
