### ISSUE TITLE
MAR - "edit" buttons should not appear for instructors

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#232]
Please remove the button for instructors

Current view
<img width="1220" alt="Screen Shot 2019-06-03 at 10 43 08 AM" src="https://user-images.githubusercontent.com/20425828/58822475-75677000-85ec-11e9-9240-946bf18aa1ac.png">

Desired view
<img width="1187" alt="Screen Shot 2019-06-03 at 10 43 26 AM" src="https://user-images.githubusercontent.com/20425828/58822479-7a2c2400-85ec-11e9-973b-f1e8add03a07.png">

**Comment by bryan-gilbert** [comment]
Fixed
