### ISSUE TITLE
Split context banner into two separate features

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#249]
Currently, we display all of the assignment data and evaluation notes in a collapsible contextual banner below the header.

Instead, I'd like to show the assignment details in a sub menu in the header on click, and show the evaluation notes without a collapse/expand button in the current contextual panel. The contextual panel should appear only if there are evaluation notes to be displayed.

If you get the functionality in, I can style it up :)

<img width="1021" alt="Screen Shot 2019-06-13 at 10 24 23 AM" src="https://user-images.githubusercontent.com/20425828/59453774-7acf7200-8dc5-11e9-852b-9633a345d5fd.png">

<img width="1021" alt="Screen Shot 2019-06-13 at 10 32 00 AM" src="https://user-images.githubusercontent.com/20425828/59454250-853e3b80-8dc6-11e9-86b7-0aa843f73130.png">

**Comment by mandily-p** [comment]
- Add instructor name to evaluation notes area
- Add resource links to assignment details area

**Comment by bryan-gilbert** [comment]
@mandily-p These are great ideas yet each might be best tracked in new issues because each needs some feature enhancements, and some discussion.  Can you please create two new feature issues and I'll add information about how these can be implemented.

**Comment by mandily-p** [comment]
I've split the remaining to do items into two tickets as noted above. Will now move this to validating column.
