### ISSUE TITLE
Discharge summary data copied from other areas of the app

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#26]
Some information in this page will be pulled from other areas of the app - please see the inputs file for more info.
Copied over from seed data dn also once the user enters new data

**Comment by bryan-gilbert** [comment]
Link to the wireframe: 
https://projects.invisionapp.com/d/main/default/#/console/14476308/308516953/preview

Before I can proceed we need to map out which precise data elements need to be imported.  Ideally, we can determine the Fully Qualified Name of the data elements that need to be imported to this page.

**Comment by mandily-p** [comment]
WIP

# Procedures and treatment
These are pulled in from the `orders` page.


# Medications administered while in care
These are pulled in from the `MAR` page.


# Discharge Rx
Pulled in from the `medication orders history`, `orders`, `lab requisitions`, and `medical imaging` pages.


# Referrals
Pulled in from the `referrals to other disciplines` page.

**Comment by bryan-gilbert** [comment]
The discharge page is now ready for some UI layout work. Plus, there might be a few Input spreadsheet edits to get things lined up well.  Ideally, we can arrange the tables in a customized manner but let the input elements get placed by the standard code.
- Over to Amanda for review, UI, comments and direction.

**Comment by mandily-p** [comment]
The form elements should be mixed in with the data that is pulled in, as per mocks. Note - all fields may not be the same as the mock, but it's pretty close. I don't know how to make edits to this page to mix form with page, but if you can give me a few pointers, I can try to work on it before Tuesday's meeting.

![Screen Shot 2019-05-30 at 10 58 14 PM](https://user-images.githubusercontent.com/20425828/58684875-a0bd3700-832e-11e9-8d47-aee7c6328f99.png)

**Comment by mandily-p** [comment]
BUG - When `Day 0` is getting pulled in from the referrals page, it's getting translated to January 1, 2000. It should remain as `Day 0`

@bryan-gilbert Let me know if this should be a separate ticket.

![Screen Shot 2019-05-30 at 11 02 48 PM](https://user-images.githubusercontent.com/20425828/58685028-3062e580-832f-11e9-8c7c-ebf08edf3847.png)

**Comment by bryan-gilbert** [comment]
@mandily-p  See line 152 of the Inputs sheet.  appointment date is a 'date' type which is a regular date.  When a user creates a referral the date is populated with a regular date via a date picker.  How did you get a 0 in this field?

**Comment by bryan-gilbert** [comment]
This happens because we do not yet have form validation.  Once we have validation this problem will go away.
