### ISSUE TITLE
Uploading documents for specific assignments

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#262]
## User story
As an admin user,
I want to be able to upload documents specific to a case
So that each case has the supporting documents it needs to be an effective teaching tool.

## Description
Cases will need documents attached to them and a way for instructors to attach them. Multiple screens will require document upload including:
- Lab requisitions

## Expected behaviour/acceptance criteria
- Admin can select a file on their hard drive to upload
- File is stored on a server
- File is linked to one or more cases
- File is accessible by students completing relevant assignments.
- Admins can delete any file
- Admins can replace any file by uploading a new file with the same name
- File list displays cases that the file is attached to.

## Unknowns
- Where do educational versions of medical information will come from?
- Are cases stored in a shared repo (and therefore so would associated files need to be)?

## Error messaging
- If a user uploads a file with the same name to something that already exists, they should be prompted to overwrite the existing file or to cancel and upload a file with a different name.

## Acceptance criteria
Bulleted list to be used for QA. Might overlap with expected behaviour and error states.

**Comment by mandily-p** [comment]
Copied from #137 

Admins will need the ability to upload documents associated with each patient profile and/or assignment under the reports and documents section of the navigation. Currently these are hardcoded in the input spreadsheet.

This will require some user flow and UI work around managing documents as well as developing the functionality.

**Comment by bryan-gilbert** [comment]
See #770
