### ISSUE TITLE
Managing authored health cases

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#273]
## User story
As an instructor user,
I want to be able to manage my authored health cases
So that I can keep them updated and relevant.

## Description
Case authors should have the ability to create and manage authored cases individually and with others using the same system

## Expected behaviour
- Create
- Duplicate
- Edit
- Delete
- Share
- Edit status (public/private/invited group)
- Provide feedback
- Use in EdEHR
- TBD

**Comment by bryan-gilbert** [comment]
essentially in place now
