### ISSUE TITLE
ExternalIds in assignment listing, should they be editable?

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#286]
### Description 
The assignment listing page allows a qualified user to edit the assignment metadata, including the externalId. This is the linking text used by LMS to identify which assignment, in the EdEHR, to launch when a user clicks a link in the LMS.

If the assignment's externalId is changed after several users have used the LMS link then the results are likely to be messed up.   If a student used the link after the change the result should be assignment not found (because the LMS external id was removed when the assignment was edited) . but if an instructor uses the link then a new assignment will be created (as expected) and then from there things are difficult to predict because of the pre-existing links between the visit record, and activity records.

### Steps to reproduce the problem

LMS link with a previously unused externalId
Instructor uses this link.
Then one or more students use the link.
Then instructor returns to EdEHR and edits the assignment changing the external Id

- try student uses original LMS link -- should fail but will likely kind-of work
- try instructor uses original LMS link -- kind-of fails. They see the original assignment with the edited external id but a new assignment is also created with the original externalId.
- try a student again.  They should go to the assignment created just above. But where will they land? who knows.

**Comment by mandily-p** [comment]
@bryan-gilbert Is this still a problem?

**Comment by bryan-gilbert** [comment]
The externalId's are not editable if there is a activity using the assignment
