### ISSUE TITLE
Unit testing SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#290]
### Description 

When building unit tests the following error can randomly appear yet there is nothing in the code that is causing it.   The unit tests are running fine then suddenly after some change in the code the error below appears.  Undoing the change doesn't make a difference. The error persists until the whole file contents are removed and replaced with the contents from another working unit test script.  As I add the original code back in the error will suddenly start again and once it's there you can't get rid of it.
```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import should from 'should';
                                                                                                    ^^^^^^
    SyntaxError: Unexpected identifier
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

The error only happens on one file. The remaining unit test run fine.
Note that the error message is exactly the same as I get when I upgrade to Babel-jest 24. See Jest issue https://github.com/facebook/jest/issues/8738

**Comment by mandily-p** [comment]
@bryan-gilbert Is this still a problem?
