### ISSUE TITLE
Page navigation should sit to the left of evaluation area

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#300]
## User story
As an instructor user,
I want to be able to view as much of the navigation at a time as possible
To minimize the amount of scrolling I need to do to navigate between pages.

## Description/Acceptance criteria
Move the navigation so that it sits to the left side of the the evaluation area as seen in the mocks below. (don't pay attention to content, it's just for layout)

<img width="1025" alt="Screen Shot 2019-08-01 at 4 54 25 PM" src="https://user-images.githubusercontent.com/20425828/62334576-12c01280-b47d-11e9-90c9-5dc0681a02de.png">

**Comment by bryan-gilbert** [comment]
@mandily-p Sure, good idea.  Note that it affects that context banner for the seed editor and student.  But that is good!
