### ISSUE TITLE
Page title on the course page should only appear once

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#307]
### Description 
When multiple courses are presented on the dashboard page, the heading "Courses" appears with each one.

It should only appear once at the top of the screen.

**Comment by viniciusarre** [comment]
@bryan-gilbert  I haven't been able to replicate this. Here's an image which shows that this is not being displayed when there's more than one course: 

<img width="1907" alt="Screen Shot 2020-03-04 at 11 55 07" src="https://user-images.githubusercontent.com/20468645/75892860-c3760200-5e10-11ea-9cc8-b360d21d1b25.png">

Also, The "Courses" heading is not being set inside the `course-list` loop. 

Let me know if this is replicated in any other way. 

Thank you!
