### ISSUE TITLE
Activity, assignment and seed text should be links to their respective pages

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#312]
## User story
As a instructor and seed editor user,
I want to be able to navigate between the necessary pages to create or update a seed easily and intuitively
So that I can save time in these tasks.

## Description
In the Dashboard > Assignments area of the app, create links within the tables to the respective pages: activity, assignment and seed text

## Expected behaviour/Acceptance criteria
- Text is presented as a link

**Comment by bryan-gilbert** [comment]
See PR #333
