### ISSUE TITLE
Input spreadsheet "one-third" class isn't being applied

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#314]
### Description 
The `is-one-third` class isn't being applied to `fieldset_row_row` elements

**Expected behaviour** 
The class shows up in the code when viewed in the inspector.

### Related
Is this perhaps related to #240 - "one-third" styles are being applied a second time to checkbox columns

**Comment by mandily-p** [comment]
I'm removing this from the project as our proposed cleanup ticket will null this. #334

**Comment by bryan-gilbert** [comment]
close as this will be addressed in the layout rework
