### ISSUE TITLE
Per seed document storage

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#315]
## User story
As a developer,
I want to be able to store documents on a per seed basis
To keep the content organized and easy to sort through.

## Description
Each seed has it's own associated document folder.

## Expected behaviour - this is not complete
- User's can upload, delete and rename files within each folder
- When users duplicate seeds, they have the option of duplicating the documents that go with it. 
- Unique names are only required within each seed's document folder, not across seeds

**Comment by bryan-gilbert** [comment]
Decided to go with a set of files for a tool consumer so that files can be shared and reused. 
Closing this issue. See #770
