### ISSUE TITLE
Edit patient banner information

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#316]
## User story
As a seed creator user,
I want to be able to edit the patient's data that shows up in patient banner at the top of the patient records
Because it's not the same across all patients.

## Description
Allow seed editors to edit the data, similar to how other parts of the page are editable.

## Expected behaviour
- Edit, save, cancel functionality
- Data becomes form fields for the user to enter data in. These might be text fields, text boxes, check boxes and/or select boxes.

**Comment by bryan-gilbert** [comment]
Done - The patient data that appears in the banner comes from the data in the ehr.
