### ISSUE TITLE
Assignment description links

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#318]
## User story
As a student user,
I want to be able to click on urls instead of copy and pasting them into the browser bar
Because  it's more intuitive and efficient.

## Description
Description text box should automatically recognize urls and format them as links.

## Expected behaviour
- Instructors can add a url into the assignment description text box and the system will automatically detect it and make it a link for students.
- the app recognizes http, https, and www prefixes to identify urls.

**Comment by bryan-gilbert** [comment]
this was added to EdEHR a long time ago. see v-text-to-html directive
