### ISSUE TITLE
Display text as written in the text box

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#319]
Display text as written in the text box. use <pre> without the monospace styling.

<img width="781" alt="Screen Shot 2019-08-10 at 11 11 48 AM" src="https://user-images.githubusercontent.com/20425828/62825404-c8672180-bb5f-11e9-9121-683ba7f31252.png">
<img width="1051" alt="Screen Shot 2019-08-10 at 11 12 05 AM" src="https://user-images.githubusercontent.com/20425828/62825406-cac97b80-bb5f-11e9-93f7-3c42f44f945a.png">

**Comment by mandily-p** [comment]
related: Line breaks do not show up in the instructor dashboard area.

<img width="781" alt="Screen Shot 2019-08-10 at 11 11 48 AM" src="https://user-images.githubusercontent.com/20425828/62825404-c8672180-bb5f-11e9-9121-683ba7f31252.png">
<img width="1051" alt="Screen Shot 2019-08-10 at 11 12 05 AM" src="https://user-images.githubusercontent.com/20425828/62825406-cac97b80-bb5f-11e9-93f7-3c42f44f945a.png">

**Comment by bryan-gilbert** [comment]
to do: where ever the assignment description is displayed use <pre> wrapping
