### ISSUE TITLE
Assignment setup validation

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#320]
## User story
As a seed editor user,
I want to be able to see at a glance if I have set up my assignment properly
To save time troubleshooting later on.

## Description
Validation message for an assignment that has been setup properly and completely.

## Expected behaviour - incomplete
- Determined by edit count and they're not using default seed

## Error states/messaging
- If a assignment is not set up properly, tell the user. "Please fix [list the error] error to complete setting up the assignment
- If an assignment is set up properly, tell the user, "This assignment is now ready to be assigned to students."

**Comment by viniciusarre** [comment]
@bryan-gilbert Is this the same as #305?

**Comment by bryan-gilbert** [comment]
@viniciusarre this was a different approach to the same problem as #305 
The idea here is server side to keep a count of each time the assignment was edited and to use this count to determine if the assignment was updated at least once.

No need to take further action. Your fix to #305 is good enough.
