### ISSUE TITLE
Clear seed data

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#322]
## User story
As a seed creator user,
I want to be able to clear seed data for an entire seed, or on a page by page basis
Because it is faster and more dependable than needing to delete data on a field by field basis

## Description
Clear seed data for entire seed or on a page by page basis.

## Expected behaviour
- Clear seed data for entire seed
- Clear data functionality for each app page
- Delete documents associated with seed

**Button options:**
- Entire seed - `Delete all seed data` and `Cancel`
- Each app page - `Delete all page data` and `Cancel` - On the dialog give the user options, `Confirm for just this page` `Confirm for all pages` So that they don't have to keep hitting the confirm button.
- Documents - `Delete all seed documents` and `Cancel`

## Error states/messaging
Show the user a "are you sure?" dialog to confirm that they want to remove the seed data. Use the message:
Title - "Are you sure you want to delete this data?"
Body - "This action cannot be undone and you will be left with an empty [page/seed - depending on what they're deleting]

**Comment by bryan-gilbert** [comment]
There now exists the ability to clear a data page form and a table.
