### ISSUE TITLE
Move data from "current" to "history"

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#327]
## User story
As a student user,
I want to be able to move data from the current visit to the relevant "history" screens
So that I can continue to work a case on a subsequent patient visit.

## Description
TBD

## Expected behaviour
TBD

## Error states/messaging
TBD

**Comment by bryan-gilbert** [comment]
Interesting concept that has merit but in the context of a seed content editor. Closing this issue because it is so far in the future we can leave it until there is a strong need.
