### ISSUE TITLE
External databases

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#33]
Some screens will have links to external databases
*** Still need to hash out which db and who pays for what.

https://docs.google.com/spreadsheets/d/1dQyiR-LB42jrLPVNkHxz2Ld8HwQD1MIl2y7LGOsos84/edit#gid=0

**Comment by mandily-p** [comment]
We don't need to link to any external db for MVP, just a few pdfs. :) That makes things a lot easier!

**Comment by mandily-p** [comment]
Just need Dave to register for a BCcampus account at https://infocentral.infoway-inforoute.ca/en/register to get access to the SNOMED-CT db.

Once we have that access, I just need to link to it on the visit details page and the code look up page and this ticket can be marked as complete.

**Comment by dshaykewich** [comment]
Emailed @mandily-p with account info.

**Comment by mandily-p** [comment]
@bryan-gilbert html isn't getting rendered in the diagnostic code modal. Can you take a look at that for me please?

<img width="998" alt="Screen Shot 2019-05-24 at 12 04 25 PM" src="https://user-images.githubusercontent.com/20425828/58350966-41d25c00-7e1c-11e9-875a-b67e0be996bb.png">

**Comment by bryan-gilbert** [comment]
The trick is to use a 'form_label' input type rather than 'text'.
https://bryan-gilbert.github.io/edehr/inside-generator/Ehr-Defs-Input-Types.html#form-label

**Comment by mandily-p** [comment]
I've got two other "databases" but they're so huge, they'll require another solution than just uploading a pdf file. I'm closing this ticket and will wait for the stakeholders or users to ask for this.
