### ISSUE TITLE
Add resource links to assignment details area

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#331]
## User story
As a student user,
I want to be able to be able to access assignment resources from within the app
To save time from needing to go back to the LMS to open them.

## Description
Add resource links under the description in the `assignment details` dropdown
<img width="1021" alt="59453774-7acf7200-8dc5-11e9-852b-9633a345d5fd" src="https://user-images.githubusercontent.com/20425828/62840319-8f0cdf80-bc4d-11e9-86d1-42ebb73aea62.png">

## Expected behaviour/acceptance criteria
- Resource links show up at the bottom of the `assignment details` dropdown
- Links open in a new tab/window

**Related to** 
#71 Access to assignment details from within EHR
#249 Split context banner into two separate features

**Comment by bryan-gilbert** [comment]
flat styling done

**Comment by mandily-p** [comment]
This isn't the ticket for flat styling. Re-opening.

**Comment by bryan-gilbert** [comment]
Right.  This is the idea to add a feature so that the text is rich text.  I explored using a markdown editor so at a minimum add some notes here about that research.

**Comment by mandily-p** [comment]
Related to #317 - Markdown editor can be used to edit assignment details.

**Comment by bryan-gilbert** [comment]
This was fixed in PR 448
