### ISSUE TITLE
Two classes are being applied to one grid element

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#367]
### Description 
I can add a new class to the input spreadsheet to control what kind of grid (how many columns and the direction) shows up, but it's being overwritten by the default `grid-left-to-right-3` class

**Expected behaviour** 
The class that is in the input spreadsheet should replace the `grid-left-to-right-3` class. This would result in the allergies field being the full width of a 1 column grid.

![Screen Shot 2019-09-06 at 3 22 57 PM](https://user-images.githubusercontent.com/20425828/64463911-a4452480-d0ba-11e9-98c2-af10e3802ee4.png)

**Comment by mandily-p** [comment]
@bryan-gilbert I thought you submitted code to fix this, but it's not working on my machine.

**Comment by bryan-gilbert** [comment]
I did add code but I misunderstood the goal.   I thought we wanted to add the class in the INPUTS to the default 3-col.  Now I got it. The intention is to replace the 3-col.  Easy fix coming in next PR

**Comment by bryan-gilbert** [comment]
Actually, we do want to keep the default 3-col IF the css class in the INPUTS is not a col defining class.  The code I will use is like this:
    groupClass () {
      let css
      const theDefault = 'grid-left-to-right-3'
      if (this.group.formCss) {
        css = this.group.formCss
        if (!this.group.formCss.includes('grid')) {
          css += ' ' + theDefault
        }
      } else {
        css = theDefault
      }
      return css
    },

**Comment by bryan-gilbert** [comment]
additional task .. remove 'foo' from ehr_group

**Comment by bryan-gilbert** [comment]
Amanda and I discussed the code above.  Basically ok just clean it up and reverse the if then else logic
