### ISSUE TITLE
ui-button styles aren't being applied to control header buttons

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#369]
I've added in the import and export bits into the `EhrPageFormControls.vue` and the `EhrPageForms.bue` but I'm not seeing the UI button styles show up like they do on other buttons. 

Once the control header buttons are loading in the styles, the edit form and cancel buttons should look like the scratch pad button and the save button should be the primary blue colour.

You'll want to merge my PR here first before looking at this ticket. https://github.com/BCcampus/edehr/pull/368

![Screen Shot 2019-09-06 at 4 29 33 PM](https://user-images.githubusercontent.com/20425828/64465926-d4dd8c00-d0c3-11e9-94bf-82de7f99a447.png)

![Screen Shot 2019-09-06 at 4 29 39 PM](https://user-images.githubusercontent.com/20425828/64465972-1d954500-d0c4-11e9-940c-c807cd6915ce.png)

**Comment by bryan-gilbert** [comment]
Fixing in next PR ... will change the mark up from 'button' to 'ui-button' and then change the action attribute.
