### ISSUE TITLE
Select label should not take up any space when not in use

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#371]
For reference, see the cardiovascular assessment modal form.

The empty select label is taking up space due to the line-height of the item. Once the label is removed, the select box moves up and is in better horizontal alignment with the row label at the left.

@bryan-gilbert Can you do a conditional statement to remove the label if it's left empty in the input spreadsheet please?

![Screen Shot 2019-09-06 at 6 44 17 PM](https://user-images.githubusercontent.com/20425828/64468222-cea4db00-d0d6-11e9-95ab-9b69dba6afab.png)

**Comment by bryan-gilbert** [comment]
add hideLabel to each select element in the Inputs

**Comment by mandily-p** [comment]
Complete.

**Comment by mandily-p** [comment]
This has been fixed.
