### ISSUE TITLE
Combo style inputs for checkboxes and text fields should only display label on checkbox

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#374]
## Description
Combo style inputs for checkboxes and text fields should only display label on checkbox. The label is currently showing on both the checkbox and the text field.

The 3 "other" text fields should not have labels taking up space either.

See the immunization page as an example.

This is what it looks like now:
<img width="693" alt="Screen Shot 2019-09-07 at 7 12 35 PM" src="https://user-images.githubusercontent.com/20425828/64482284-de3e2580-d1a3-11e9-8f22-98bfd9bbe941.png">

This is what it should look like:
<img width="708" alt="Screen Shot 2019-09-07 at 7 15 00 PM" src="https://user-images.githubusercontent.com/20425828/64482285-e5653380-d1a3-11e9-95c7-a784de34549d.png">

**Comment by mandily-p** [comment]
Related to #371

**Comment by mandily-p** [comment]
@bryan-gilbert I'm confused as to why this is in my bucket. What do I need to do here?

**Comment by bryan-gilbert** [comment]
One of us needs to modify the code that generates the check with date to add the hideLabel css attribute. Easiest if I do this.

**Comment by bryan-gilbert** [comment]
fixed in next PR
