### ISSUE TITLE
Vital signs: Graph doesn't load until chart tab is clicked

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#378]
## To reproduce:

Enter the application as a instructor viewing an assignment for the first time
Click on a student who has completed at least one vital sign entry
Click on the Vital signs page
See that there is no graph
Click on the chart tab, and then back to the graph tab
See that the graph is now present

**Comment by bryan-gilbert** [comment]
this also happens for student users. They just need to add some data to the vital signs and then go to another page and return.

**Comment by bryan-gilbert** [comment]
no longer a problem
