### ISSUE TITLE
Vital signs: Opening the vital signs form from the chart page breaks layout

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#379]
## To reproduce:

Enter the application as a student
Navigate to the vital signs page
Click on the chart tab, graph tab and back to chart tab.
Click on the Add vital signs button
See that the modal is off the screen to the right side of the page.
Close the modal
See that the chart page cannot be scrolled.

**Comment by bryan-gilbert** [comment]
yes there is a problem with the add on the chart tab. it should open the dialog and be modal

**Comment by bryan-gilbert** [comment]
Is this fixed. Investigation needed.
