### ISSUE TITLE
Warn instructors when evaluation notes aren't saved.

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#383]
## User story
As an instructor user,
I want to be reminded to save a students evaluation notes if I try to navigate to another screen or student
So that I don't lose my unsaved work.

## Description
Prompt instructors to save before navigating away from a student they are currently evaluating.

## Expected behaviour/Acceptance criteria
- The user should be forced to make an explicit decision.
- If the "next" button is clicked, prompt the user with the following message: "Your evaluation notes have not been saved. What would you like to do?"
buttons: "Save and **next**", "Discard notes and continue"
- If the "previous" button, link to the dashboard, help, or the LMS are clicked, prompt the user with the following message: "Your evaluation notes have not been saved. What would you like to do?"
buttons: "Save and **continue**", "Discard notes and continue"

**Comment by bryan-gilbert** [comment]
Plus handle the case the user navigates away from the page.
The solution is to use Vue route guards.  See the code in ehr-helper.js
beforeRouteLeave   and beforeUnloadListener
 We need to use code like this in the EhrEvaluationInput.  
Note to get to this component you need to log into Moodle with the instructor user id and ‘evaluate’ a student’s work.
