### ISSUE TITLE
Vital signs graph looks low res

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#384]
The Vital Signs graph looks low res compared to the rest of the app. I'm not sure how canvas renders this, but is there a way to increase the DPI?

<img width="431" alt="Screen Shot 2019-09-19 at 4 04 28 AM" src="https://user-images.githubusercontent.com/20425828/65239005-d3806c00-da92-11e9-8558-e9559bc723a5.png">

**Comment by bryan-gilbert** [comment]
I'm fairly certain it is fixable and it's something I thought I dealt with before ... so keep this open.
