### ISSUE TITLE
MAR - PRN and stat medications need an adjusted form to be filled in when meds are administered

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#392]
## User story
As a student user,
I want to be able to enter details around when a PRN (take as needed) medication is administered to a patient
Because it needs to be documented in the same way as a prescribed medication on a set timeline.

## Description
All medications need the MAR modal form whether they are on a schedule, as needed, stat, or once

## Expected behaviour/Acceptance criteria
- User can click on a "Add MAR" button to launch a modal
- Scheduled time does not appear

**Comment by bryan-gilbert** [comment]
I'd like to see a mock up of the screen for this.

**Comment by mandily-p** [comment]
I just realized I can just change the label in the input spreadsheet and it negates the need for two different forms. I'll go ahead and close this.

![Screen Shot 2019-12-24 at 7 35 27 AM](https://user-images.githubusercontent.com/20425828/71418582-0735d980-2620-11ea-90d6-a5c02756e19b.png)

**Comment by bryan-gilbert** [comment]
sweet
