### ISSUE TITLE
Digital signing

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#401]
**Replace the identification fields at the top of each form with a digital signing feature after data has been filled in.**
This is similar to the process that would happen in a professional setting, and would benefit students to learn before hitting a work environment. Included in this “signature” area should also be some kind of messaging that reminds the user that their signature is a confirmation that they have reviewed the entered information and that it is correct. 

Update June 2020.
Once https://github.com/BCcampus/edehr/issues/674 is complete use the assignment persona data to complete this digital signing feature. 

- remove the record header from displaying a the top of the forms (remove from Inputs)
- in the dialog footer add the following dynamic text and a checkbox. Disable the submit button until the checkbox is checked (default unchecked).
"Certified correct ${persona name}, ${persona profession}.  Hospital date: ${assignment date} ${assignment time in 24hr format}"

See comment below June 20th

**Comment by bryan-gilbert** [comment]
Would this happen on a per form basis?  I'll assume yes. So this translates to making a confirmation dialog to replace those top fields.  The data in this dialog, I believe, should come from a 'login' process. Let's assume there is a dialog for this that the student needs to invoke before they can do editing.
- block editing until 'logged in'  or require 'login' 
- add some form of login dialog
- establish the 'day' and 'time' from that login?
- create a signature dialog.
Most of the effort will be in designing the flow.  The dialogs and such will be easy.  Won't be hard to clean up the inputs spreadsheet if we do so at all. We might use the record heard element to indicate to use this new flow.

**Comment by mandily-p** [comment]
I'm not going to assume anything at the moment. I've reached out to stakeholders for some screens to see how this is done currently in commercial products.

**Comment by mandily-p** [comment]
Instead of at the top, I think we can just move the record header to the bottom of each modal/page form and style it a little differently so that it stands out better.

Depending on whether a "sign in" functionality has been added or not, this can either be a straight move for the record header (Step 1), or a "sign" button that automagically adds their name, profession, date and time.(Step 2)

**Comment by bryan-gilbert** [comment]
The issue description was updated three days ago.  In addition to the description:

All forms that have a record header will now have the form footer adjusted as described above. Plus, when the form is submitted the record heard values will be inserted into the record as if the record header was a part of the form data. (e.g. the end result in the data will look the same as the data does now. So be careful to place the fields into the same location they are now.
