### ISSUE TITLE
Dashboard: Visually indicate "current assignment"

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#440]
## User story
As an admin user,
I want to be able to see at a glance what assignment I'm working on
Because  it makes the process easier to manage.

## Description
Investigate a visually distinct style and/or layout to highlight the assignment the admin is currently working on.

**Comment by bryan-gilbert** [comment]
Note that the code currently scrolls to and expands the activity the teacher selected in the LMS.  Or in other words, when an instructor clicks on an activity in their LMS they EdEHR will scroll this activity into the window and expand the activity to show the class list.

**Comment by mandily-p** [comment]
Completed.
