### ISSUE TITLE
Default "empty" seed

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#456]
## User story
As a admin user,
I want to be able to start with an empty seed and add in my own data
Because it's easier when it's in context to the application.

## Description
When a user boots up a new instance of the app, there should be two seeds by default: Erin Johns full case study and an "empty" seed.

**Comment by bryan-gilbert** [comment]
All new consumers come with a default empty seed.
Perhaps this issue should be changed to say "All new consumers need to provide a sample Erin Jones" seed as well as the default empty seed.  The sample Erin Jones seed can be edited.

IF that is the desired way to write this issue then we should include the official default Erin Jones seed in code.  I.e. start by attaching this seed to this issue.

**Comment by mandily-p** [comment]
@bryan-gilbert What user are referring to when you say "consumer"? This ticket was specifically targetted at the admin types who would be setting up assignments.

The patient's name is Erin Johns, not Erin Jones. :)

Seeds are located here: https://drive.google.com/open?id=1Yv4TSHw3qS-qbWyxtnEGoyEftcPPjWWI

**Comment by mandily-p** [comment]
The current flow is broken down into a few different steps when a new assignment is created. It's given a "default seed" and then the user needs to go in and change the seed in the dropdown to the one they actually want to use. For now we can continue using that flow and if it become a problem or confusing we can open up another issue documenting why and what needs to change.

Closing this ticket now.
