### ISSUE TITLE
Student does not see seed data

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#473]
### Description 

This broke during development of the instructor seed editor experience.  The seed data for the student is no longer loaded when the student enters the application.  This break is mainly due to the complexity of loading process.

**Expected behaviour** 

As a student, I expect to see the assignment seed data plus any data I entered before.  I expect that I can refresh the browser and see the same.

As an instructor, while evaluating the student's work, I expect to see the current student's work merged with the assignment's seed data.  I expect that I can refresh the browser and see the same.

(This is a new desired feature.) As an instructor, while reviewing (not editing) an assignment I expect to see the assignment seed data and be able to add to this data. The additions are not saved (or at least they might be saved but they are cleared the next time I enter).

As a content editor I expect to see the seed data as stored the last time it was edited.

**Comment by mandily-p** [comment]
Where did this requirement come from @bryan-gilbert ?

> (This is a new desired feature.) As an instructor, while reviewing (not editing) an assignment I expect to see the assignment seed data and be able to add to this data. The additions are not saved (or at least they might be saved but they are cleared the next time I enter).

**Comment by bryan-gilbert** [comment]
The "requirement" is my way of saying the course content creator and instructor can both visit the EdEHR and preview the assignment data (seed).  I figure they might like to be able to make edits while doing this preview knowing these edits will be tossed when they leave the preview.

But, this bug report is not meant to say we need this requirement now.  I was just outlining, for the developer who needed to fix the bug, the range of ways that users need to interact with the seed data.

Having this helped while working on https://github.com/BCcampus/edehr/pull/476

https://github.com/BCcampus/edehr/pull/476 resolves this issue
