### ISSUE TITLE
Welcome page for unregistered users

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#482]
Prerequisite to issue #454 

## User story
As a curious academic user who comes to the EdEHR via, say, Google
I want to be able to look around the application and try some things out
Because I want to know if the EdEHR is suitable for use in my classroom

## Description
When I arrive at the EdEHR without coming via a LMS I will see a welcome page that will allow me to visit the EdEHR

## Expected behaviour
- page explains what the EdEHR is about and what the user can do
- has a simple form with Name, Email and a log in button
- If the user has visited before (e.g. that email address is in some list) then restore their previous work. Otherwise create a new visitor record and present the EdEHR, perhaps with some seed data
- Allow the user to make 10 saves in one 24 hr period.

## Task list
To complete this issue will depend on several tasks
- wireframe of the welcome page(s) with forms
- client side redirect all unauthenticated requests to the welcome page
- form validation (e.g. non empty fields, reasonable limits to data size (i.e. under 400 characters per field or maybe less, basic validation of email address (80% solution)
- composition of a LTI request from the client
- solve the question about what tool consumer to create and use
- limit the api login requests from a given IP address to 20? per day.
- solve the question of what assignment is to be shown and seed
- make sure the user can save data to their assignment but limit the number of saves to 20?, or maybe 200? per day.

Each of the above will be new issues to be linked to this issue.

**Comment by mandily-p** [comment]
This is low on the priority list. This shouldn't be on a project board right now.

**Comment by bryan-gilbert** [comment]
The Demo mode resolves this issue
