### ISSUE TITLE
Mock welcome page and redirect

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#483]
## Task
To support issue #482 
we will redirect unauthenticated users to a new page
this will be the first step of the demo mode

## Details
- in the client code add a route after each guard
- if the user has arrived via LTI then let them proceed otherwise
- redirect them to a new main page
- create a new main empty page
- add routing to this page.

```
router.afterEach((to): void => {
  try {
if not authenticated
... route to the new page
  } catch (error) {
    console.error('Router afterEach', error)
  }
})

On the main page put a simple h1 element
"Welcome to the EdEHR"

Then add the following text:
"We are working to let you see the EdEHR in a demonstration mode. Please come back soon"

**Comment by mandily-p** [comment]
This is a low priority item. It should not be on a project board.
