### ISSUE TITLE
Demo - Login form and api

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#485]
## Task
To support issue #482
we will add a login form and api for demo users
because we need to identify the user in some way to let them interact with the EdEHR

There will not be a password requirement. Just an email address that passes a 80% is-it-an-email-address test. (e.g. a basic email address regular expression test)

## Details
- Add a form to the main welcome page. Add fields for Given, Family names and Email address
- Validate the form
- Post the form to the API
- On the API create a new end point /demo with controller. 
- Accept the above post from the client 
- In memory record the IP address from the request.
- If the IP address has been seen 20 times in the last 24hrs then fail the request
- redirect the successful request (see the redirect in the server/src/mcr/lti controller)

**Comment by mandily-p** [comment]
Demo mode is not a high priority item. It should not be on a project board.
