### ISSUE TITLE
Integumentary assessment - WIP

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#486]
## User story
As a student user,
I want to be able to ______________
Because  _________________

## Description
Add integumentary assessment as seen in attached PDF to the EdEHR.
[Provincial Wound Assessment & Treatment Flowsheet.pdf](https://github.com/BCcampus/edehr/files/3938012/Provincial.Wound.Assessment.Treatment.Flowsheet.pdf)

## Expected behaviour/acceptance criteria
- "Mark location of wound" image is not included
- All fields are needed and should be on the form. (This is a standard form used across BC)
- References to the pain assessment and progress notes are made in the paper form, but we don't need to pull in information from those into this.
- Located in the menu between musculoskeletal and pain assessments
- Wound size should be in cm
- Remove visit count
- Change the text "Treatment done as per Treatment Plan" to "Treatments as per interprofessional plan of care"
- One wound per assessment modal, but that wound can have multiple days worth of data added to it. Although for pilot, one wound be enough.

**Comment by bryan-gilbert** [comment]
See #802
