### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#500]
## User story
As an app user,
I want to be able to be able to see the header when I'm in the dashboard/admin area
So that I don't have to scroll up on a long page to navigate to the next area that I want to go

## Description
Make the header sticky in the "outside" pages. 

## Expected behaviour
- When the user scrolls down, the app header stays at the top of the screen.

This may be related/a good issue to work on in combination with #79 - Sticky footer on short pages.

**Comment by bryan-gilbert** [comment]
Resolved in PR#513
