### ISSUE TITLE
Error on medication page

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#548]
**Describe the bug**
There is a console error when a user visits the Medication page

**To Reproduce**
1. Go to medication page
2. Open the developers console log and see the error.

**Expected behavior**
No error will appear meaning the code is functioning correctly.

**Comment by viniciusarre** [comment]
@bryan-gilbert have you been able to reproduce this error after merging? I tested it again and haven't been able to reproduce it. Please, let me know if there's any further problem. I will be moving this to Validation for now...
