### ISSUE TITLE
Unable to send evaluation notes to student when activity is closed

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#706]
**Describe the bug**
While an activity is open any student can submit their work and then the instructor can evaluate their work. The instructor can also choose to share the evaluation work with the student so that the student can return to the EdEHR and see the instructor's comments.
But once the activity is closed the instructor can not send the evaluation to the student.

**Comment by viniciusarre** [comment]
@bryan-gilbert Is this still an issue? I couldn't replicate it. I did the following in my attempt to replicate it: 

1. Submitted the assignment as a student;
2. Then login as an instructor and close the activity;
3. After the activity has been closed, the instructor can still send back to the student (please refer to the screenshots below for more details).

After closing the activity and evaluating:
![image](https://user-images.githubusercontent.com/20468645/92304532-334a7e00-ef55-11ea-8fb7-9d1e1cfffda7.png)

After sending back to the student:
![image](https://user-images.githubusercontent.com/20468645/92304581-a3f19a80-ef55-11ea-9e93-0f02be7cc824.png)

Please, let me know your thoughts on it.

Thank you!

**Comment by bryan-gilbert** [comment]
Thank you for testing this
