### ISSUE TITLE
Instructor dashboard does not display all items in assignment 

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#76]
## Description
When expanding multiple assignments in the dashboard, some student records disappear.

## To replicate
1. Go to the instructor's dashboard.
2. Expand the 2nd assignment, see two student names
3. Expand the first assignment, see one student name
4. See that the 2nd assignment is missing a student record and a grey box is there instead.

Two students are in the second assignment when the first assignment is collapsed.
<img width="1304" alt="screen shot 2019-02-12 at 5 28 53 pm" src="https://user-images.githubusercontent.com/20425828/52737138-79f61300-2f80-11e9-8696-0faea9593c1c.png">

Only one student is in the second assignment when the first assignment is expanded.
<img width="1298" alt="screen shot 2019-02-12 at 5 29 09 pm" src="https://user-images.githubusercontent.com/20425828/52737137-79f61300-2f80-11e9-8090-c964ee1bc62e.png">

**Comment by bryan-gilbert** [comment]
This seems to work without a problem for me. Did you fix it?

**Comment by mandily-p** [comment]
I didn't fix it. Maybe it was resolved with another PR! Magic!

**Comment by mandily-p** [comment]
Looks like this still isn't fixed. I'm throwing this back into the to do column

**Comment by bryan-gilbert** [comment]
This is resolved with the latest PR.
