### ISSUE TITLE
Input fields with unit of measurement to the right

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#78]
Some input fields have the unit of measurement to the right of it. This means that the input can't take up 100% of the column width.

We'll need a way to indicate this kind of input in the spreadsheet.

An example of this is on the respiratory assessment screen.
<img width="756" alt="screen shot 2019-02-13 at 1 07 15 pm" src="https://user-images.githubusercontent.com/20425828/52744031-55099c00-2f90-11e9-9646-096ec55e249e.png">

**Comment by bryan-gilbert** [comment]
@mandily-p   Code is in place ... can you now please style this

**Comment by mandily-p** [comment]
Waiting to style this until after I take a crack at replacing flexbox with grid.
