### ISSUE TITLE
Change orientation of 4 tables add stacked fields

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#83]
The medications screen table should be organized with each record being displayed in a row.

**Comment by mandily-p** [comment]
I had an action item to review this ticket to make sure it's still relevant - it is. :)

**Comment by mandily-p** [comment]
Diagnostic codes table should be horizontal as well. I'm updated the ticket title to be "3 tables"

**Comment by mandily-p** [comment]
Medications: https://invis.io/DPK5BBWVSR9#/308516941_Setup_-_Current_Visit-_Medication_Orders
Referrals: https://projects.invisionapp.com/d/main#/console/14476308/308516939/preview
Diagnostic codes: https://projects.invisionapp.com/d/main#/console/14476308/308508057/preview
Intervention codes: https://projects.invisionapp.com/d/main#/console/14476308/308508058/preview

**Comment by bryan-gilbert** [comment]
The elements shown in the wireframe for Diagnostic codes does not match the Inputs spreadsheet. There are more elements in the worksheet than appear on the wireframe.
E.g. Name, Profession, Day, Time, ICD-10 database, Condition, Diagnosis code, Diagnosis type, Prefix, Diagnosis cluster  vs  Condition, Diagnosis code, Diagnosis type, Prefix, Diagnosis cluster

**Comment by bryan-gilbert** [comment]
Dito for referrals:
Name, Profession, Day, Time, Referral name, Referral profession, Appointment date, Appointment time, Status  vs a different set of elements in the wireframe:  Referred by, Referred on, Referred to, Appointment and Status

**Comment by mandily-p** [comment]
The input spreadsheet is the source of truth. Many of the screens changed after our last stakeholder meetings and to save time, I didn't update the wireframes to match.

Is it clear to you what needs to be grouped and what can be solo? Depending on how you set this up, I may be able to go into the input spreadsheet and play around with the groupings after you've set them up too. :)

**Comment by mandily-p** [comment]
Discussed the ability to adjust numbers in the tableColumn column in the input spreadsheet. IE 1, 1, 1, 2, 3, - All of the labels with "1" would be grouped together in a column in a list.

**Comment by bryan-gilbert** [comment]
-[] rework how tableCells are composed in the code generation and replace the array of elements with an array of either: (a) stacks of elements or (b) either a stack or the element when there is just one element. One element is the most common.
See setupColumnData in ehr-helper

**Comment by mandily-p** [comment]
@bryan-gilbert Would it be possible to add another column to the input spreadsheet for a table column label override? It would be useful to provide a summative heading.

**Comment by mandily-p** [comment]
@bryan-gilbert Would it be possible to add another column to the input spreadsheet for a table column label override? It would be useful to provide a summative heading.
