### ISSUE TITLE
Navigation functionality - step 2

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#84]
If the user is on a smaller screen, they cannot see all of the left side navigation. They also can't scroll to see the rest.

I'd like to propose a two step solution. This is the second of those features.
The use should have the ability to collapse and expand each top level section. The user can click anywhere within that rectangle to collapse/expand it. They don't need to click directly on the icon.

We can use the `plus` and `minus` fontawesome icons. 
We might need to expand the side nav to 250px to acomodate.

<img width="234" alt="screen shot 2019-02-13 at 8 56 37 pm" src="https://user-images.githubusercontent.com/20425828/52763766-ef3e0400-2fd1-11e9-98f7-64cc865781c2.png">

**Comment by mandily-p** [comment]
Edit: The user CAN scroll to see all of the menu

**Comment by bryan-gilbert** [comment]
Consider those + - indicators. They could be important to show users the nested nature of the nav area

**Comment by bryan-gilbert** [comment]
We added the ability for the nav menu to collapse on small screens.
